# Generated by Django 3.1.4 on 2021-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210725_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='weekly_view',
            new_name='view',
        ),
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='brand_banner'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brand_logo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_logo'),
        ),
    ]
