# Generated by Django 3.1.4 on 2021-07-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210728_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
