# Generated by Django 3.1.4 on 2021-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
