# Generated by Django 3.1.4 on 2021-08-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210802_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='noti_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
