# Generated by Django 3.1.4 on 2021-08-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210806_0047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.AddField(
            model_name='brand',
            name='view',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
