# Generated by Django 3.1.4 on 2021-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
