# Generated by Django 3.1.4 on 2021-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_banner_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ocr_text',
            field=models.TextField(null=True),
        ),
    ]
